---
title: "hw5"
author: "Yingxi Ji"
date: "11/5/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

# Problem 1
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

# Write a function to fill the NA. 
fill_na = function(x) {
  if (is.numeric(x)) { 
    replace_na(x, mean(x, na.rm = TRUE))
    }
  else if (is.character(x)) { 
     replace_na(x, "virginica")
  }
}

irs_filled_df = (map_dfr(iris_with_missing, fill_na, .id = "input"))
```

# Problem 2
```{r}
files = list.files(path = "data")

agg_data = tibble(files) %>% 
  mutate(
    file_content = map(files, ~ read_csv(file.path("./data", .)))
  ) %>% 
  unnest()

tidy_data = agg_data %>%
  rename(group_id = "files") %>% 
  pivot_longer(
    week_1:week_8, 
    names_to = "week", 
    values_to = "value"
  )

tidy_data %>% 
  ggplot(aes(x = week, y = value)) +
  geom_line(aes(group = group_id, color = group_id)) +
  labs(
        title = "Counts for control and experimental arms",
        subtitle = "over eight-week observation period",
        x = "Week",
        y = "Count")

```

We can see the pattern that the experiment group has higher values and increase along with the time. On the other hand, the control group has a reletively small variance and small change along the time. 

